export const healthyRecipes = [
  {
    name: "Quinoa Buddha Bowl",
    description: "A nutritious bowl packed with quinoa, roasted vegetables, and tahini dressing",
    ingredients: ["1 cup quinoa", "2 cups mixed vegetables", "1/4 cup tahini", "2 tbsp lemon juice", "1 tbsp olive oil", "Salt and pepper"],
    instructions: ["Cook quinoa according to package instructions", "Roast vegetables at 400°F for 20 minutes", "Mix tahini with lemon juice and olive oil", "Combine all ingredients in a bowl"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    calories: 450,
    protein: 15,
    carbs: 65,
    fat: 18,
    category: 'lunch' as const,
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400',
    isHealthy: true
  },
  {
    name: "Greek Yogurt Parfait",
    description: "Protein-rich breakfast with Greek yogurt, berries, and granola",
    ingredients: ["1 cup Greek yogurt", "1/2 cup mixed berries", "1/4 cup granola", "1 tbsp honey", "1 tbsp chia seeds"],
    instructions: ["Layer yogurt in a glass", "Add berries and granola", "Drizzle with honey", "Top with chia seeds"],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 320,
    protein: 20,
    carbs: 35,
    fat: 8,
    category: 'breakfast' as const,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    isHealthy: true
  },
  {
    name: "Grilled Salmon with Asparagus",
    description: "Heart-healthy salmon with roasted asparagus and lemon",
    ingredients: ["4 oz salmon fillet", "1 bunch asparagus", "1 lemon", "2 tbsp olive oil", "Garlic", "Salt and pepper"],
    instructions: ["Season salmon with salt and pepper", "Grill salmon for 4-5 minutes per side", "Roast asparagus with olive oil and garlic", "Serve with lemon wedges"],
    prepTime: 10,
    cookTime: 15,
    servings: 1,
    calories: 380,
    protein: 35,
    carbs: 8,
    fat: 22,
    category: 'dinner' as const,
    image: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=400',
    isHealthy: true
  },
  {
    name: "Avocado Toast with Poached Egg",
    description: "Nutritious breakfast with healthy fats and protein",
    ingredients: ["2 slices whole grain bread", "1 ripe avocado", "2 eggs", "Cherry tomatoes", "Salt and pepper", "Red pepper flakes"],
    instructions: ["Toast bread slices", "Mash avocado with salt and pepper", "Poach eggs", "Spread avocado on toast", "Top with poached egg and tomatoes"],
    prepTime: 10,
    cookTime: 8,
    servings: 2,
    calories: 340,
    protein: 16,
    carbs: 28,
    fat: 20,
    category: 'breakfast' as const,
    image: 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400',
    isHealthy: true
  },
  {
    name: "Mediterranean Chickpea Salad",
    description: "Fresh and filling salad with Mediterranean flavors",
    ingredients: ["2 cups chickpeas", "1 cucumber", "Cherry tomatoes", "Red onion", "Feta cheese", "Olive oil", "Lemon juice", "Fresh herbs"],
    instructions: ["Drain and rinse chickpeas", "Dice cucumber and tomatoes", "Slice red onion thinly", "Combine all ingredients", "Dress with olive oil and lemon juice"],
    prepTime: 15,
    cookTime: 0,
    servings: 3,
    calories: 290,
    protein: 12,
    carbs: 35,
    fat: 12,
    category: 'lunch' as const,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=400',
    isHealthy: true
  },
  {
    name: "Overnight Oats with Berries",
    description: "Easy make-ahead breakfast with oats, berries, and nuts",
    ingredients: ["1/2 cup rolled oats", "1/2 cup milk", "1 tbsp chia seeds", "1/2 cup mixed berries", "1 tbsp honey", "1/4 cup nuts"],
    instructions: ["Mix oats, milk, and chia seeds", "Refrigerate overnight", "Top with berries, honey, and nuts", "Enjoy cold"],
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    calories: 350,
    protein: 12,
    carbs: 45,
    fat: 14,
    category: 'breakfast' as const,
    isHealthy: true
  },
  {
    name: "Lentil and Vegetable Curry",
    description: "Protein-rich curry with lentils and mixed vegetables",
    ingredients: ["1 cup red lentils", "2 cups mixed vegetables", "1 can coconut milk", "2 tbsp curry powder", "1 onion", "2 cloves garlic", "Ginger"],
    instructions: ["Sauté onion, garlic, and ginger", "Add curry powder and cook 1 minute", "Add lentils, vegetables, and coconut milk", "Simmer 20 minutes until tender"],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    calories: 320,
    protein: 18,
    carbs: 42,
    fat: 12,
    category: 'dinner' as const,
    isHealthy: true
  },
  {
    name: "Grilled Chicken and Quinoa Salad",
    description: "High-protein salad with grilled chicken and quinoa",
    ingredients: ["4 oz grilled chicken breast", "1/2 cup cooked quinoa", "Mixed greens", "Cherry tomatoes", "Cucumber", "Olive oil", "Lemon juice"],
    instructions: ["Grill chicken breast until cooked through", "Cook quinoa according to package instructions", "Combine greens, tomatoes, cucumber", "Top with chicken and quinoa", "Dress with olive oil and lemon"],
    prepTime: 15,
    cookTime: 15,
    servings: 1,
    calories: 420,
    protein: 35,
    carbs: 30,
    fat: 18,
    category: 'lunch' as const,
    isHealthy: true
  },
  {
    name: "Sweet Potato and Black Bean Bowl",
    description: "Nutritious bowl with roasted sweet potato and black beans",
    ingredients: ["1 large sweet potato", "1/2 cup black beans", "1/4 avocado", "2 tbsp salsa", "1 tbsp lime juice", "Cilantro", "Cumin"],
    instructions: ["Roast sweet potato cubes at 400°F for 25 minutes", "Heat black beans with cumin", "Assemble bowl with sweet potato and beans", "Top with avocado, salsa, and cilantro"],
    prepTime: 10,
    cookTime: 25,
    servings: 1,
    calories: 380,
    protein: 14,
    carbs: 65,
    fat: 8,
    category: 'dinner' as const,
    isHealthy: true
  },
  {
    name: "Green Smoothie Bowl",
    description: "Nutrient-packed smoothie bowl with spinach and fruits",
    ingredients: ["1 cup spinach", "1 banana", "1/2 cup mango", "1/2 cup coconut milk", "1 tbsp almond butter", "Granola", "Coconut flakes"],
    instructions: ["Blend spinach, banana, mango, and coconut milk", "Pour into bowl", "Top with almond butter, granola, and coconut flakes"],
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    calories: 340,
    protein: 8,
    carbs: 52,
    fat: 14,
    category: 'breakfast' as const,
    isHealthy: true
  },
  {
    name: "Mixed Nuts",
    description: "Healthy snack with almonds, walnuts, and cashews",
    ingredients: ["1/4 cup almonds", "1/4 cup walnuts", "1/4 cup cashews"],
    instructions: ["Mix all nuts together", "Store in airtight container"],
    prepTime: 2,
    cookTime: 0,
    servings: 1,
    calories: 160,
    protein: 6,
    carbs: 6,
    fat: 14,
    category: 'snack' as const,
    image: 'https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=400',
    isHealthy: true
  },
  {
    name: "Apple with Almond Butter",
    description: "Simple and nutritious snack with fiber and healthy fats",
    ingredients: ["1 medium apple", "2 tbsp almond butter"],
    instructions: ["Slice apple", "Serve with almond butter for dipping"],
    prepTime: 3,
    cookTime: 0,
    servings: 1,
    calories: 190,
    protein: 6,
    carbs: 20,
    fat: 12,
    category: 'snack' as const,
    image: 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=400',
    isHealthy: true
  },
  {
    name: "Greek Yogurt with Berries",
    description: "Protein-rich snack with antioxidants",
    ingredients: ["1/2 cup Greek yogurt", "1/4 cup mixed berries", "1 tsp honey"],
    instructions: ["Add berries to yogurt", "Drizzle with honey"],
    prepTime: 2,
    cookTime: 0,
    servings: 1,
    calories: 120,
    protein: 10,
    carbs: 15,
    fat: 2,
    category: 'snack' as const,
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400',
    isHealthy: true
  }
];